version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  ipfs:
    build: ./ipfs
    volumes:
      - ./data:/app/data
  dao:
    build: ./dao
    ports:
      - "7000:7000"
